drone:
  name: "iris"
  max_velocity: 0.2
  min_velocity: -0.2
  safety_distance: 1.0
  sensor_data_dimension:
    depth_camera:
      width: 64
      height: 48
    rplidar: 360
  initial_position:
    empty_room: [[ 0,  0,  0],
                 [ 1,  1,  0],
                 [-1,  1,  0],
                 [ 1, -1,  0],
                 [-1, -1,  0]]
    empty_room_obstacle: [[ 3, -2,  0],
                          [-3, -3,  0],
                          [ 3,  3,  0],
                          [-3,  2,  0]]
    concave: [[ -3, 0,  0]]
    3rooms: [[ 0,  0,  0],
             [ 0, -6,  0],
             [ 7,  0,  0],
             [ 7, -6,  0],
             [14,  0,  0],
             [14, -6,  0]]
    EE405: [[ -1.5, 0.5,  0]]
    benchmark1: [[-3,  1,  0],
                 [-3,  0,  0],
                 [-3, -1,  0]]
    benchmark2: [[-3,  1,  0],
                 [-3,  0,  0],
                 [-3, -1,  0]]
    benchmark3: [[-3,  1,  0],
                 [-3,  0,  0],
                 [-3, -1,  0]]
    benchmark3_active: [[-3,  1,  0],
                        [-3,  0,  0],
                        [-3, -1,  0]]
goal:
  name: "spotlight"
  reach_threshold: 0.5
  initial_position:
    empty_room: [[ 2.5,  2.5,  0],
                 [-2.5,  2.5,  0],
                 [ 2.5, -2.5,  0],
                 [-2.5, -2.5,  0]]
    empty_room_obstacle: [[ 2,  0,  0],
                          [ 0, -2,  0],
                          [ 0,  2,  0],
                          [-2.5, 0,  0]]
    concave: [[ 3, 0,  0]]
    3rooms: [[-1,  1, 0],
             [ 1,  1, 0],
             [-1, -3, 0],
             [ 1, -3, 0],
             [-1, -7, 0],
             [ 1, -7, 0],
             [ 5,  1, 0],
             [ 9,  1, 0],
             [ 5, -3, 0],
             [ 9, -3, 0],
             [ 5, -7, 0],
             [ 9, -7, 0],
             [13,  1, 0],
             [15,  1, 0],
             [13, -3, 0],
             [15, -3, 0],
             [13, -7, 0],
             [15, -7, 0]]
    EE405: [[ 1.5, -0.5,  0]]
    benchmark1: [[ 2.25,  0.5,  0],
                 [ 2.25,  0,  0],
                 [ 2.25, -0.5,  0]]
    benchmark2: [[ 2.25,  0.5,  0],
                 [ 2.25,  0,  0],
                 [ 2.25, -0.5,  0]]
    benchmark3: [[ 2.25,  0.5,  0],
                 [ 2.25,  0,  0],
                 [ 2.25, -0.5,  0]]
    benchmark3_active: [[ 2.25,  0.5,  0],
                        [ 2.25,  0,  0],
                        [ 2.25, -0.5,  0]]
reward_criteria:
  dense:
    coeff:
      lambda_p: 1
      lambda_w: 0.0015915494309189533 # 1/(200*pi)
      lambda_g: 0.15
      epsilon: 0.05
    no_motion: -0.05
    reach: 1
    collision: 0
  sparse:
    reach: 1
    collision: 0
